services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 1m30s
      timeout: 30s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/requirements.txt:/app/requirements.txt
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-client
    environment:
      API_BASE_URL: ${API_BASE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data:
